### ISSUE TITLE
Crash on selecting certain biomes in singleplayer

### ISSUE THREAD

**Issue by rinart73** [MattCzyr/NaturesCompass#22]
**Version:** 1.12.2-1.5.1
**Forge:** 1.12.2 - 14.23.5.2768

Server crashes when I'm trying to search for:
Corrupted Sands - https://pastebin.com/pbXerwrT
Ominous Woods - https://pastebin.com/Ew1fxUju
Tropical Island - https://pastebin.com/nFjYxkmK

**Comment by MattCzyr** [comment]
Please replace your NaturesCompass-1.12.2-1.5.1.jar file with the following 1.5.2 beta file:

https://www.dropbox.com/s/m0pqzaoi0oze88d/NaturesCompass-1.12.2-1.5.2-beta.jar?dl=0

Then, try searching for these biomes again (under the exact same conditions) and let me know if the issue persists.

**Comment by rinart73** [comment]
> Does the lagging only start after you search for a biome?

Yes

> Does the lagging only occur after searching for specific biomes, as opposed to ALL biomes or ALL BoP biomes?

From what I can see, biomes that previously crashed the game now causing lags, plus Natures Compass still doesn't show them

> Is there no lag when searching for these biomes with the old (1.5.1 release) version, as opposed to with the new (1.5.2 beta) version?

No, it just crashes instead in the 1.5.1

**Comment by MattCzyr** [comment]
Since 1.5.2-beta only lags the game instead of crashing it, I'm tempted to believe that the new issue is just that the biomes you're searching for are too far away to be found, and your game times out before the search returns "not found." Try going in naturescompass.cfg and lowering the max samples. If it still times out, try also raising the sample space modifier and lowering the distance modifier. Be sure to test with the same biomes again.
