### ISSUE TITLE
Enhancement: Find Another Biome

### ISSUE THREAD

**Issue by JoshMayberry** [MattCzyr/NaturesCompass#28]
Awesome Mod! Very helpful, except it can only find one of each Biome.
Once a biome for a specific type is found, it keeps taking me to the same one.
I would like to search for a type of biome in the world, and then find another of that same biome in a different spot.

**Comment by MattCzyr** [comment]
Thanks for the suggestion. I've gotten this request before but ultimately have decided not to add it for now because this kind of feature may end up being too powerful. There's a fine line between QOL and OP and this may be the feature that crosses that line. My only suggestion would be to travel far away from the biome in question and see if there's another one that gets discovered instead.

**Comment by JoshMayberry** [comment]
Makes sense. Regardless, thank you for the mod.
