### ISSUE TITLE
Unable to search for biome in multiplayer

### ISSUE THREAD

**Issue by Alan19** [MattCzyr/NaturesCompass#65]
When using the Nature's Compass on any biome (including the one I'm in), it is searching forever. It was working when the world was created, but stopped working after I reached the biome I was searching for and stopped after looking for another biome.

Forge: 1.15.2 - 31.2.9
Nature's Compass: NaturesCompass-1.15.2-1.8.5.jar

**Comment by MattCzyr** [comment]
Does searching with a Nature's Compass work for anyone else on the server? Are you doing anything out of the ordinary with the compass when trying to search with it? For example, moving the compass around your inventory while it's searching? Dropping/picking it up while it's searching?

Ask the server owner to show you the console log from after you try to search for a biome, and post that here. The two relevant lines I'll be looking at include one that begins with "Starting search ...", and then another a bit later that begins with "Search succeeded ...", "Search failed ...", or "Can't find a compass ...".

**Comment by Alan19** [comment]
It seems like it only works for certain biomes. We have Biomes o Plenty on the serve but forgot to set the world type to that when we started. We were able to get it to work with some vanilla biomes, but not others. I'll see if I could get a server log.

**Comment by Alan19** [comment]
According to the server owner, it says "Starting search" and searches forever for Taiga Mountains without producing an error.

**Comment by Macleykun** [comment]
> According to the server owner, it says "Starting search" and searches forever for Taiga Mountains without producing an error.

So i've did a bit of digging, and found out about the following:
Taiga Mountains is not a Biomes o Plenty biome, i did an export of Bundle O Plenty (OTG generated world/biomes) and looked up the name given:

ID | Registry name | Biome name | temp. | temp cat | rain | snow | oceanic | BiomeType | BiomeDictionary.Type | Valid for
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
33 | openterraingenerator:overworld_mega_taiga_mountains | Mega Taiga Mountains | 0.20 | MEDIUM | 0.80 | false | false | &nbsp; | COLD, CONIFEROUS, FOREST, HILLS | stronghold

So, i believe your issue is actually related to this issue instead: https://github.com/MattCzyr/NaturesCompass/issues/14
Would like to know if this is correct. Biomes o Plenty generated world (not the OTG) should should work fine.

**Comment by MattCzyr** [comment]
Upon revisiting this issue, it sounds like it could be one of two things:

1. You mentioned you forgot to set the world type to Biomes o' Plenty when you first created it. This could cause some issues with biomes not being where the generator now thinks they should be.
2. It could also be that the biomes you're trying to locate are simply too far away to be located given your current config settings. Check my comment on #14 for more info on this and what you can do about it.
