### ISSUE TITLE
Config

### ISSUE THREAD

**Issue by Correlander** [MattCzyr/NaturesCompass#85]
When the biome blacklist in the config becomes too long, it crashes the game on start. Also, a suggestion, you should add an option to remove all sub-biomes etc. That is what I was trying to do, so instead  of the list being cluttered by dark forest, dark forest hills, etc. which are all part of the same biome, just different parts of it,  would not show up. I can send my config and crash log if you need confirmation, but only adding more than a line of biomes to the blacklist caused it to crash.

**Comment by MattCzyr** [comment]
Please post your config and crash log.

**Comment by Correlander** [comment]
[crash-2021-04-10_15.06.31-client.txt](https://github.com/MattCzyr/NaturesCompass/files/6294150/crash-2021-04-10_15.06.31-client.txt)

Config is normally .toml but I had to change it to .txt to upload it. Content shows the same.
[naturescompass-common.txt](https://github.com/MattCzyr/NaturesCompass/files/6294157/naturescompass-common.txt)

**Comment by MattCzyr** [comment]
This is not an issue with the length of the biome blacklist in your config, but rather that your blacklist is malformed. There's a colon instead of a quotation mark after `minecraft:savanna`, and there's a missing quotation mark directly before `minecraft:tall_birch_hills`. When you fix these two issues, your config works properly.
